services:
  # NestJS app
  app:
    build: .
    ports:
      - "3001:3001" 
    env_file: .env  
    environment:
      - NODE_ENV=${NODE_ENV:-development}  
      - DATABASE_URL=${DATABASE_URL} 
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - MQTT_BROKER_URL=${MQTT_BROKER_URL}  
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC=PTUD/DT027/IOT/power_all_summary,PTUD/DT027/IOT/fridge01/telemetry,PTUD/DT027/IOT/ac01/telemetry,PTUD/DT027/IOT/fridge01/telemetry,PTUD/DT027/IOT/wash01/telemetry,PTUD/DT027/IOT/tv01/telemetry,PTUD/DT027/IOT/light01/telemetry  # Combine multiple topics (comma-separated for subscribe)
      - MQTT_CA_PATH=/app/certs/emqxsl-ca.crt  
    depends_on:
      - db
    volumes:
      - .:/app 
      - ./certs:/app/certs:ro  

  db:
    image: postgres:15
    restart: always
    env_file: .env  
    environment:
      POSTGRES_DB: smart_energy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data: